//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHangHai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_thongtinthuyenvienEntities : DbContext
    {
        public db_thongtinthuyenvienEntities()
            : base("name=db_thongtinthuyenvienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_coquan> tb_coquan { get; set; }
        public virtual DbSet<tb_danhsachthuyenvien> tb_danhsachthuyenvien { get; set; }
        public virtual DbSet<tb_doanhnghiep> tb_doanhnghiep { get; set; }
        public virtual DbSet<tb_loaitau> tb_loaitau { get; set; }
        public virtual DbSet<tb_taikhoan> tb_taikhoan { get; set; }
        public virtual DbSet<tb_tau_doanhnghiep> tb_tau_doanhnghiep { get; set; }
        public virtual DbSet<tb_thuyen> tb_thuyen { get; set; }
        public virtual DbSet<tb_thuyenvien> tb_thuyenvien { get; set; }
    }
}
