//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHangHai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_coquan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_coquan()
        {
            this.tb_loaitau = new HashSet<tb_loaitau>();
            this.tb_tau_doanhnghiep = new HashSet<tb_tau_doanhnghiep>();
            this.tb_thuyen = new HashSet<tb_thuyen>();
        }
    
        public int MaCoQuan { get; set; }
        public string TenCoQuan { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> TruongCoQuan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_loaitau> tb_loaitau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tau_doanhnghiep> tb_tau_doanhnghiep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_thuyen> tb_thuyen { get; set; }
    }
}
