//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHangHai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_doanhnghiep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_doanhnghiep()
        {
            this.tb_tau_doanhnghiep = new HashSet<tb_tau_doanhnghiep>();
        }
    
        public string MSDoanhNghiep { get; set; }
        public string TenDoanhNghiep { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string SoFax { get; set; }
        public string NgayCap { get; set; }
        public string NoiCap { get; set; }
        public Nullable<int> CoQuanPheDuyet { get; set; }
        public Nullable<int> ChuDoanhNghiep { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tau_doanhnghiep> tb_tau_doanhnghiep { get; set; }
    }
}
