//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHangHai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_loaitau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_loaitau()
        {
            this.tb_thuyen = new HashSet<tb_thuyen>();
        }
    
        public int LoaiTau { get; set; }
        [Required(ErrorMessage ="Không được để trống.")]
        [Display(Name ="Loại tàu")]
        public string TenLoai { get; set; }
        [Display(Name ="Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }
        [Display(Name ="Cơ quan thêm")]
        public Nullable<int> CoQuanThem { get; set; }
    
        public virtual tb_coquan tb_coquan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_thuyen> tb_thuyen { get; set; }
    }
}
