//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHangHai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_taikhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_taikhoan()
        {
            this.tb_thuyenvien = new HashSet<tb_thuyenvien>();
        }
    
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> CoQuanDuyet { get; set; }
        public Nullable<bool> TKThuyenVien { get; set; }
        public Nullable<bool> TKCoQuan { get; set; }
        public Nullable<bool> TkDoanhNghiep { get; set; }
        public string EmailDangKy { get; set; }
        public string SDTDangKy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_thuyenvien> tb_thuyenvien { get; set; }
    }
}
