//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHangHai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_thuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_thuyen()
        {
            this.tb_danhsachthuyenvien = new HashSet<tb_danhsachthuyenvien>();
            this.tb_tau_doanhnghiep = new HashSet<tb_tau_doanhnghiep>();
        }

        [Display(Name ="Mã tàu")]
        public int MaTau { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        [Display(Name ="Số hiệu")]
        public string SoHieu { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        [Display(Name ="Tên tàu")]
        public string TenTau { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        public string IMO { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        [Display(Name = "Quốc tịch")]
        public string QuocTich { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        [Display(Name = "Loại tàu")]
        public Nullable<int> LoaiTau { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        [Display(Name = "Tổng dung tích máy")]
        public Nullable<double> TongDungTichMay { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        [Display(Name = "Tổng công suất máy chính")]
        public Nullable<double> TongCSMayChinh { get; set; }
        [Required(ErrorMessage = "Không được để trống.")]
        [Display(Name = "Chủ tàu")]
        public Nullable<int> ChuTau { get; set; }
        [Display(Name = "Cơ quan phê duyệt")]
        public Nullable<int> CoQuanPheDuyet { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual tb_coquan tb_coquan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_danhsachthuyenvien> tb_danhsachthuyenvien { get; set; }
        public virtual tb_loaitau tb_loaitau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tau_doanhnghiep> tb_tau_doanhnghiep { get; set; }
        public virtual tb_thuyenvien tb_thuyenvien { get; set; }
    }
}
