//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTHangHai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_thuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_thuyen()
        {
            this.tb_danhsachthuyenvien = new HashSet<tb_danhsachthuyenvien>();
            this.tb_tau_doanhnghiep = new HashSet<tb_tau_doanhnghiep>();
        }
    
        public int MaTau { get; set; }
        public string SoHieu { get; set; }
        public string TenTau { get; set; }
        public string IMO { get; set; }
        public string QuocTich { get; set; }
        public Nullable<int> LoaiTau { get; set; }
        public Nullable<double> TongDungTichMay { get; set; }
        public Nullable<double> TongCSMayChinh { get; set; }
        public Nullable<int> ChuTau { get; set; }
        public Nullable<int> CoQuanPheDuyet { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual tb_coquan tb_coquan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_danhsachthuyenvien> tb_danhsachthuyenvien { get; set; }
        public virtual tb_loaitau tb_loaitau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tau_doanhnghiep> tb_tau_doanhnghiep { get; set; }
        public virtual tb_thuyenvien tb_thuyenvien { get; set; }
    }
}
